#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Meridian — Neon Postgres setup (interactive, one-shot)
#
# What it does:
#   1. Installs neonctl if missing
#   2. Opens neon.tech auth in your browser (OAuth — you approve in the browser)
#   3. Creates a project named "meridian" (skips if it already exists)
#   4. Pulls the connection string
#   5. Writes it to ~/meridian/.env.local alongside a fresh ADMIN_TOKEN
#   6. Applies migrations + seeds the database
#   7. Restarts the meridian systemd service (if present)
#
# Nothing is stored outside your machine. You can re-run it any time —
# it's idempotent.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

APP_DIR="${APP_DIR:-$HOME/meridian}"
PROJECT_NAME="${PROJECT_NAME:-meridian}"
DB_NAME="${DB_NAME:-neondb}"
ROLE="${ROLE:-neondb_owner}"
SERVICE_NAME="${SERVICE_NAME:-meridian}"

BLUE=$'\033[0;34m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[0;33m'; RED=$'\033[0;31m'; NC=$'\033[0m'
log(){ echo "${BLUE}▸${NC} $*"; }
ok(){ echo "${GREEN}✓${NC} $*"; }
warn(){ echo "${YELLOW}!${NC} $*"; }
err(){ echo "${RED}✗${NC} $*" >&2; }

if [ ! -d "$APP_DIR" ]; then
  err "$APP_DIR not found. Run the main deploy script first."
  exit 1
fi

# ── 1. Ensure neonctl is installed ──────────────────────────────────
if ! command -v neonctl >/dev/null 2>&1; then
  log "Installing neonctl globally via npm"
  npm install -g neonctl
fi
ok "neonctl $(neonctl --version 2>/dev/null || echo 'installed')"

# ── 2. Auth ─────────────────────────────────────────────────────────
if ! neonctl me >/dev/null 2>&1; then
  warn "neonctl needs to authenticate — a browser window will open."
  warn "If SSH'd in without a browser, copy the URL it prints and open it locally."
  neonctl auth
fi
ok "Authenticated as $(neonctl me -o json 2>/dev/null | grep -o '"email":"[^"]*"' | cut -d'"' -f4 || echo 'unknown')"

# ── 3. Project ──────────────────────────────────────────────────────
PROJECT_ID="$(neonctl projects list -o json | node -e "
  const items = JSON.parse(require('fs').readFileSync(0, 'utf8'));
  const arr = Array.isArray(items) ? items : (items.projects || []);
  const hit = arr.find(p => p.name === process.argv[1]);
  process.stdout.write(hit ? hit.id : '');
" "$PROJECT_NAME")"

if [ -z "$PROJECT_ID" ]; then
  log "Creating Neon project '$PROJECT_NAME'"
  PROJECT_ID="$(neonctl projects create --name "$PROJECT_NAME" -o json | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).project.id)")"
else
  ok "Reusing Neon project $PROJECT_ID"
fi

# ── 4. Connection string ────────────────────────────────────────────
log "Pulling connection string…"
DATABASE_URL="$(neonctl connection-string --project-id "$PROJECT_ID" --role-name "$ROLE" --database-name "$DB_NAME" 2>/dev/null || true)"
if [ -z "$DATABASE_URL" ]; then
  # Fallback: use default role
  DATABASE_URL="$(neonctl connection-string --project-id "$PROJECT_ID")"
fi
ok "Got connection string (ending …${DATABASE_URL##*/})"

# ── 5. Write .env.local (preserves existing keys if present) ────────
ENV_FILE="$APP_DIR/.env.local"
ADMIN_TOKEN="${ADMIN_TOKEN:-$(openssl rand -hex 32)}"
if [ -f "$ENV_FILE" ]; then
  # Keep existing ADMIN_TOKEN if present
  if grep -q '^ADMIN_TOKEN=' "$ENV_FILE"; then
    ADMIN_TOKEN="$(grep '^ADMIN_TOKEN=' "$ENV_FILE" | head -n1 | cut -d= -f2-)"
  fi
fi

cat > "$ENV_FILE" <<EOF
# Generated by setup-neon.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=$DATABASE_URL
ADMIN_TOKEN=$ADMIN_TOKEN
NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:4040}
EOF
chmod 600 "$ENV_FILE"
ok "Wrote $ENV_FILE (0600)"

# ── 6. Migrate + seed ────────────────────────────────────────────────
cd "$APP_DIR"
log "Generating migrations (if needed)…"
DATABASE_URL="$DATABASE_URL" npx drizzle-kit generate >/dev/null || warn "drizzle-kit generate emitted a warning; continuing"

log "Applying migrations…"
DATABASE_URL="$DATABASE_URL" npm run db:migrate

log "Seeding canonical corpus…"
DATABASE_URL="$DATABASE_URL" npm run db:seed

# ── 7. Rebuild + restart service (best effort) ──────────────────────
log "Rebuilding web bundle…"
npm run build

if systemctl list-unit-files "$SERVICE_NAME.service" >/dev/null 2>&1; then
  log "Restarting $SERVICE_NAME systemd unit…"
  sudo systemctl restart "$SERVICE_NAME"
  ok "Service restarted"
fi

echo
echo "────────────────────────────────────────────────────────────"
echo "${GREEN}  Neon connected${NC}"
echo "────────────────────────────────────────────────────────────"
echo "  Project:      $PROJECT_NAME  ($PROJECT_ID)"
echo "  Env file:     $ENV_FILE"
echo "  Admin token:  $ADMIN_TOKEN"
echo "  Save the admin token — you'll paste it when turning on workers."
echo
echo "  Next: configure GitHub Actions secrets:"
echo "    bash $APP_DIR/scripts/setup-secrets.sh"
echo "────────────────────────────────────────────────────────────"
